In [1]:
import pandas as pd

print("Pandas is ready!")

Pandas is ready!

In [1]:

import pandas as pd

columns = [
    "Sepal Length",
    "Sepal Width",
    "Petal Length",
    "Petal Width",
    "Species"
]

df = pd.read_csv(
    "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data",
    header=None,
    names=columns
)

df.head()

   Sepal Length  Sepal Width  Petal Length  Petal Width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [2]:
print(df.shape)

(150, 5)

In [3]:
df["Sepal Length"].mean()

np.float64(5.843333333333334)

In [4]:
# Select numerical columns
numeric_data = df.select_dtypes(include="number")

# Calculate descriptive statistics
summary = pd.DataFrame({
    "Mean": numeric_data.mean(),
    "Median": numeric_data.median(),
    "Mode": numeric_data.mode().iloc[0],
    "Standard Deviation": numeric_data.std()
})

summary["25th Percentile"] = numeric_data.quantile(0.25)
summary["50th Percentile"] = numeric_data.quantile(0.50)
summary["75th Percentile"] = numeric_data.quantile(0.75)
summary["Minimum"] = numeric_data.min()
summary["Maximum"] = numeric_data.max()

summary.round(3)

,Mean,Median,Mode,Standard Deviation,25th Percentile,50th Percentile,75th Percentile,Minimum,Maximum
Sepal Length,5.843,5.80,5.0,0.828,5.1,5.80,6.4,4.3,7.9
Sepal Width,3.054,3.00,3.0,0.434,2.8,3.00,3.3,2.0,4.4
Petal Length,3.759,4.35,1.5,1.764,1.6,4.35,5.1,1.0,6.9
Petal Width,1.199,1.30,0.2,0.763,0.3,1.30,1.8,0.1,2.5

In [5]:
summary.round(3).to_csv("iris_summary_statistics.csv")

print("Summary statistics saved successfully!")

Summary statistics saved successfully!

In [6]:
print("Mean vs Median:")
print(summary[["Mean", "Median"]].round(3))

print("\nStandard Deviation:")
print(summary["Standard Deviation"].round(3))

Mean vs Median:
               Mean  Median
Sepal Length  5.843    5.80
Sepal Width   3.054    3.00
Petal Length  3.759    4.35
Petal Width   1.199    1.30

Standard Deviation:
Sepal Length    0.828
Sepal Width     0.434
Petal Length    1.764
Petal Width     0.763
Name: Standard Deviation, dtype: float64

In [ ]:
 Conclusion

In this task, descriptive statistics were calculated for the Iris dataset using Excel, Python, and Pandas. Mean, median, mode, standard deviation, and percentiles were used to summarize the numerical columns. Comparing mean and median helped identify possible skewness, while standard deviation showed the variability of the measurements. This task improved my understanding of data analysis and statistical interpretation.